 //Elements
 const input = document.getElementById("answer");
 const result = document.getElementById("result");
 const description = document.getElementById("description");

 input.addEventListener("keyup", function () {
   event.preventDefault();
   if (event.keyCode === 13) document.getElementById("submit").click();
 });

 var goodFood = {
   apple: "The seeds are toxic and core is a choking hazard, so be careful.",
   apricot: "Remove the core (choking hazard and toxic), and don't give too much as it contains small amounts of cyanide.",
   banana: "",
   ananas: "",
   blueberr: "",
   cantaloupe: "Remove the seeds and skin.",
   cranberr: "",
   mango: "Healthy for dogs, but make sure its without the peel and pit (skin is hard to digest, pit is choking hazard).",
   orange: "High in sugar and can cause upset stomach.",
   pear: "The seeds are toxic and core is a choking hazard, so only give your dog bit-size slices of pear.",
   pineapple: "Can cause nausea and diarrhea in larger amount.",
   strawberr: "",
   watermelon: "Without the rind or seeds, which can be choking hazard and cause digestive problems.",
   corn: "Never give your dog the corn cob!",
   broccoli: "Dogs can eat raw or cooked broccoli. Too much can cause digestive problems.",
   cauliflower: "",
   cabbage: "",
   asparagus: "On some occasions may cause vomiting or diarrhea if uncooked.",
   pepper: "",
   "brussels sprouts": "",
   carrot: "",
   celer: "Cut it into bite-size pieces to avoid choking hazard.",
   cucumber: "",
   lettuce: "",
   pea: "Only fresh / frozen peas. Avoid canned peas as they are usually heavily salted.",
   pumpkin: "",
   zucchini: "",
   potato: "But raw potatoes contain solanine which is toxic to dogs!",
   blackberr: "",
   kiwi: "Remove the skin if you can (because it can cause digestive problems) and not give kiwi as a whole so the dog wont swallow it and choke / create blockage.",
   plum: "The pit is toxic and there is choking hazard, so only give your dog bit-size slices of plum.",
   tangerine: "Not toxic but high in sugar and can cause upset stomach.",
   nectarine: "Not toxic but high in sugar and can cause upset stomach.",
   egg: "But raw eggs could give your dog salmonella, and too much of it can cause biotin deficiency.",
   popcorn: "OK for dogs, but make sure doesn't have salt or too much oil in it.",
   bread: "Contains lots of salt and sugar, so it is not healthy.",
   oatmeal: "",
   chicken: "Avoid seasonings or sauces. Raw Chicken can give your dog salmonella and may contain other unhealthy bacteria.",
   pork: "Not including ham and bacon which are bad. Also avoid seasonings or sauces. Raw Pork can give your dog salmonella and may contain other unhealthy bacteria.",
   beef: "Avoid too spicy ones and also those with onion or garlic flavour.",
   turkey: "Avoid seasoning or sauces, and only boneless and skinless turkey.",
   rice: "Brown rice is better for dogs since white rice is highly processed. Brown rice has more vitamins, minerals and fiber.Avoid slating the rice.",
   shrimp: "Remove the shell to prevent your dog from choking. Raw can make your dog sick.",
   peanut: "Unsalted peanuts are harmless but high in fat, so better not feed them too much to your dog.",
   quinoa: "",
   wheat: "Some dogs are allergic to wheat.",
   grain: "",
   pasta: "Not toxic but cooked with salt. Also some dogs are allergic to wheat.",
   spaghetti: "",
   stew:"",
   pretzel: "",
   roll: "",
   olive: "",
   "iceberg lettuce": "",
   artichoke: "",
   beet: "",
   ginger: "",
   bean: "Make sure no salted. Broad Beans can be dangerous.",
   
   parsnip: "",
   salmon: "Remove bones to avoid choking hazard. Generally contains Omega 3 which is very good for dogs. Raw can contain Neorickettsia helminthoeca parasite, which could be fatal to dogs.",
   fig: "",
   tomato: "Ripe tomatoes are generally safe, but green tomatoes are very toxic for dogs. Better just avoid to be sure.",
   chickpea: "OK for dogs, but only if cooked.",
   vinegar: "",
   lamb: "",
   buckwheat: "",
   thyme: "",
   kale: "",
   soya: "",
   dogfood: "",
   "dog food": "",
   water: "Lol :D",
   guava: "",
   papaya: "",
   capsicum: "",
   "soy milk": "",
   lentil: "",
   steak: "",
   smelts: "",
   sardine: "",
   anchovies: "",
   herring: "",
   mackerel: "",
   tuna: "Just cooked; avoid raw ones.",
   venison: ""
 }

 var moderateFood = {
   eggplant: "Eggplants are not inheritly toxic to dogs, but some dogs are allergic and could become very ill from it. Also its bad if the dog has kidney problems.",
   bacon: "Rich in fat and usually contains large quantities of salt and seasoning which may be harmful.",
   ham: "Rich in fat and usually contains large quantities of salt and seasoning which may be harmful.",
   cinamon: "Not toxic but in large quantities can irritate their digestive system. Also don't let them sniff it directly, can cause them coughing and breathing problems.",
   raspberr: "",
   spinach: "",
   coconut: "",
   salt: "",
   cheese: "",
   cashew: "",
   almonds: "",
   "cottage cheese": "Very limited consumption; if it causes diarrhea or digestive upset, stop giving it to your dog entirely.",
   cottagecheese: "Very limited consumption; if it causes diarrhea or digestive upset, stop giving it to your dog entirely.",
   honey: "",
   milk: "",
   yogurt: "Only in a moderate amount. If it causes diarrhea or digestive upset, stop giving it to your dog entirely. Important: avoid sweetened ones containing xylitol. Xylitol is super dangerous for dogs. If your dog ate yogurt that contains xylitol, contact your vet immediately.",
   butter: "",
   cereals: "Ocasionally, as a treat in small portions, but never substitute a full meal with cereal, since feeding your dog too often with cereal could lead to obesity and diabetes. Avoid giving your dog cereal containing chocolate or a high level of sugar.",
   flour: "",
   cherry: "",
   salad: "",
   walnut: "Fresh walnuts aren’t dangerous in small amounts, but moldy ones are.",
   tofu: "",
   mozzarella: "",
   pickle: "",
   mayo: "Normal mayo is safe, but make sure to avoid those that contain xylitol. Xylitol is super dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately.",
   ketchup: "Normal ketchup is safe, but make sure to avoid those that contain xylitol. Xylitol is super dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately",
   prawn: "Make sure to cook it and remove shell.",
   squash: "",
   ham: "",
   bone: "Give your dog raw bones than cooked ones. Pork and poultry bones or cooked bones of any kind are strictly forbidden since bone shards can cause choking and serious damage to the dog’s mouth or throat",
   "peanut butter": "Normal peanut butter is safe, but make sure to avoid those that contain xylitol. Xylitol is super dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately.",
   peanutbutter: "Normal peanut butter is safe, but make sure to avoid those that contain xylitol. Xylitol is super dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately.",
   "sour cream": "Only very limited amount since most of the dogs have problems digesting lactose; an kind of food containing milk could be risky to your dog. If it causes diarrhea or digestive upset, stop giving any kind of milk product to your dog",
   sourcream: "Only very limited amount since most of the dogs have problems digesting lactose; an kind of food containing milk could be risky to your dog. If it causes diarrhea or digestive upset, stop giving any kind of milk product to your dog",
   pistachio: ""
 }

 var harmfulFood = {
   xylitol:"Xylitol is very dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately.",
   lemon: "",
   lime: "",
   grapefruit: "It’s best to call your veterinarian. Grapefruit rinds and plant parts are toxic to dogs, the flesh is acidic but not toxic.",
   onion: "",
   garlic: "",
   rhubarb: "",
   grape: "",
   mushroom: "",
   raisin: "",
   "macadamia nuts": "",
   "macadamia nut": "",
   macadamianuts: "",
   macadamianut: "",
   coffee: "",
   tea: "",
   cappuccino: "",
   latte: "",
   alcohol: "",
   nutmeg: "",
   yeast: "",
   "ice cream": "",
   icecream: "",
   chives: "",
   "garlic powder": "",
   "yeast dough": "",
   yeastdough: "",
   gum: "",
   nutella: "",
   cola: "",
   pepsi: "",
   soda: "",
   jalapeno: "",
   "spring onion": "",
   sugar: "",
   chilli: "",
   chocolate: "If your dog ate chocolate, call your veterinarian immediately",
   fish: "",
   scallions: "",
   scallion: "",
   "chilli pepper": "",
   "french fries": "",
   chips: "",
   beer: "",
   wine: "",
   champagne: "Your pet should consume zero alcohol, but if they do, they require an emergency vet visit",
   whiskey: "",
   whisky: "",
   tequila: "",
   vodka: "",
   absinthe: "",
   rum: "",
   brandy: "",
   snaps: "",
   cider: "",
   baileys: "",
   liqueur: "",
   gin: "",
   avocado: "",
   pizza: "It doesn't provide much nutrition for your dog. It also could contain onion or garlic which are dangerous for your dog.",
   fries: "",
   sausage: "Not recommended because sausages are too spicy and salty for your dog. Avoid sausages with onion or garlic flavour",
   oreo: "",
   "apple cider": "",
   pepper: "",
   leek: "",
   brisket: "",
   mustard: "",
   licorice: "",
   "chewing gum": "",
   xylitol: "",
   crisp: "",
   "dark chocolate": "",
   gravy: "",
   caramel: "",
   coke: "",
   shallot: "",
   sprite: "",
   jelly: "",
   jam: "",
   "poppy seed": "",
   poppyseed: "",
   "poppy seeds": "",
   orbit: "If your dog recently ate gum with xylitol in it, contact your vet immediately",
   marshmallow: "",
   cand: "Some candies contain xylitol which is very dangerous for dogs. If your dog ate food that contains xylitol, contact your vet immediately.",
   pomegranate: "",
   Marijuana:"Can cause hypothermia, excessively low or high heart rates, low blood pressure, vomiting, diarrhea, incontinence, coma, or death."
 }


 function foodChecker() {

   if (Object.keys(goodFood).some(word => input.value.toLowerCase().trim().includes(word))) {
     result.textContent = "Yep! You can give " + input.value + " to your dog! 👍😊";
     description.textContent = goodFood[input.value];
     document.body.style.backgroundColor = "#2EC4B6";
     return;
   }
   if (Object.keys(harmfulFood).some(word => input.value.toLowerCase().trim().includes(word))) {
     result.textContent = "Nope! You shouldn't give " + input.value + " to your dog! 😯😦🙅‍";
     description.textContent = harmfulFood[input.value];
     document.body.style.backgroundColor = "#FF5351";
     return;
   }
   if (Object.keys(moderateFood).some(word => input.value.toLowerCase().trim().includes(word))) {
     result.textContent = "Hmmm, maybe. Please, read the description below 👇";
     description.textContent = moderateFood[input.value];
     document.body.style.backgroundColor = "#fcba03";
     return;
   }
   result.textContent = "Sorry, we don't have info about this food. ☹️ Is it actually a food?🤔";
 }
